# Banco de dados
spring.datasource.url=jdbc:postgresql://db:5432/tasksdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Java 21 - Virtual Threads
spring.threads.virtual.enabled=true

# Desabilita cache de arquivos estáticos (dev)
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-cache=true
